
const INIT_GRID = "INIT_GRID"
const INIT_DISPLAY = "INIT_DISPLAY"
const INIT_POSITION = "INIT_POSITION"
const UPDATE_GRID_SIZE = "UPDATE_GRID_SIZE"
const UPDATE_DISPLAY_SIZE = "UPDATE_DISPLAY_SIZE"
const UPDATE_POSITION = "UPDATE_POSITION"
const UPDATE_GRID = "UPDATE_GRID"
const UPDATE_DISPLAY = "UPDATE_DISPLAY"
